language: rust
sudo: required

after_success: curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    secure: j4YyOuekzEZuQpjP5uSnq7JVrmyIIqgLTpDb0EEo2cBY7C1q8Ii8f0FvY+hPVidPjNj2CPS+GM1PDWUYlLtZxo000L3MhRt7Me/0dOsWKJ0kP22J+hmijNFilDefKyLgXyozO9AwK+VbKnCKcwJF+T41GwjUN55NCqrW3jAhj5Qxr0NzAktUYZuwSghBIpk7ekyOK5TW2QTPF/0mwC2NQXORtEwA25AvWDJhmCGpbOIcB00eS3VHWJ5LPqYJypjNMYJDylJonO8xPA2oNhQ3ka84r9zMcTiNWJQPWKHXn9R/+KerW2qt3bR6tsiKG+mE5RBRSh8sHvws7lSuZuEORwWhTlGss0qodNdK7szSn1OvHyQ/mT0qK7PHVvbwrsupkfjmBbyH2pzAHoSk+UKKKyaEFk9A41qeg3CzBONI+faDWd2qwlsElpHWiH4m+JmKtwRQ2qHxQdifUxbikkzyVdNbIQUyGKMOVWfe+6yvwBt8jnHfwVIAnABb2X1Y16cEKaee0n4vjlPTJaXu5kpG4WsvFN8rcoCswtfqEHD7pSTdbg64lBopcj6tcBH2XGv96+Iv99+2Zf5OsSD5ABPWzu4iO0A9xIn6RM3P3Q4Kc/XVpnxtNdxX7rTb3ZJJx8sbxBAsdgPi7s/1YC8zexp9GmNU/AY+KRfQ6ZyiFMKMtwU=

notifications:
  email: false
